// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PutniNalogAPI.Models;

namespace PutniNalogAPI.Migrations
{
    [DbContext(typeof(PutniNalogContext))]
    partial class PutniNalogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PutniNalogAPI.Models.Auti", b =>
                {
                    b.Property<int>("IdAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Kilometraza")
                        .HasColumnType("int");

                    b.Property<string>("MarkaAuta")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NazivAuta")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RegistracijaAuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VrstaPrijevoza")
                        .HasColumnType("int");

                    b.HasKey("IdAuto");

                    b.ToTable("Autis");
                });

            modelBuilder.Entity("PutniNalogAPI.Models.Korisnici", b =>
                {
                    b.Property<int>("IdKorisnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ImeKorisnik")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PrezimeKorisnik")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdKorisnik");

                    b.ToTable("Korisnicis");
                });

            modelBuilder.Entity("PutniNalogAPI.Models.KorisniciNalog", b =>
                {
                    b.Property<int>("idKorisniciNalog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("KorisnikIdKorisnik")
                        .HasColumnType("int");

                    b.Property<int?>("PutniNalogIdPutniNalog")
                        .HasColumnType("int");

                    b.Property<int>("idKorisnik")
                        .HasColumnType("int");

                    b.Property<int>("idPutniNalog")
                        .HasColumnType("int");

                    b.HasKey("idKorisniciNalog");

                    b.HasIndex("KorisnikIdKorisnik");

                    b.HasIndex("PutniNalogIdPutniNalog");

                    b.ToTable("KorisniciNalogs");
                });

            modelBuilder.Entity("PutniNalogAPI.Models.Lokacije", b =>
                {
                    b.Property<int>("IdLokacija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLokacija");

                    b.ToTable("Lokacijes");
                });

            modelBuilder.Entity("PutniNalogAPI.Models.PutniNalog", b =>
                {
                    b.Property<int>("IdPutniNalog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AutiIdAuto")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("IdAuto")
                        .HasColumnType("int");

                    b.Property<int>("IdOdrediste")
                        .HasColumnType("int");

                    b.Property<int>("IdPolaziste")
                        .HasColumnType("int");

                    b.Property<int>("KmPocetak")
                        .HasColumnType("int");

                    b.Property<int>("KmZavrsetak")
                        .HasColumnType("int");

                    b.Property<string>("Komentar")
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OdredisteIdLokacija")
                        .HasColumnType("int");

                    b.Property<int?>("PolazisteIdLokacija")
                        .HasColumnType("int");

                    b.Property<string>("RazlogPutovanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VrijemePolazak")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("VrijemePovratak")
                        .HasColumnType("datetime");

                    b.HasKey("IdPutniNalog");

                    b.HasIndex("AutiIdAuto");

                    b.HasIndex("OdredisteIdLokacija");

                    b.HasIndex("PolazisteIdLokacija");

                    b.ToTable("PutniNalogs");
                });

            modelBuilder.Entity("PutniNalogAPI.Models.Troskovi", b =>
                {
                    b.Property<int>("IdTrosak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("IdPutniNalog")
                        .HasColumnType("int");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OpisTrosak")
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PutniNalogIdPutniNalog")
                        .HasColumnType("int");

                    b.HasKey("IdTrosak");

                    b.HasIndex("PutniNalogIdPutniNalog");

                    b.ToTable("Troskovis");
                });

            modelBuilder.Entity("PutniNalogAPI.Models.KorisniciNalog", b =>
                {
                    b.HasOne("PutniNalogAPI.Models.Korisnici", "Korisnik")
                        .WithMany("KorisniciNalogs")
                        .HasForeignKey("KorisnikIdKorisnik");

                    b.HasOne("PutniNalogAPI.Models.PutniNalog", "PutniNalog")
                        .WithMany("KorisniciNalogs")
                        .HasForeignKey("PutniNalogIdPutniNalog");

                    b.Navigation("Korisnik");

                    b.Navigation("PutniNalog");
                });

            modelBuilder.Entity("PutniNalogAPI.Models.PutniNalog", b =>
                {
                    b.HasOne("PutniNalogAPI.Models.Auti", "Auti")
                        .WithMany("PutniNalogs")
                        .HasForeignKey("AutiIdAuto");

                    b.HasOne("PutniNalogAPI.Models.Lokacije", "Odrediste")
                        .WithMany("PutniNalogOdrediste")
                        .HasForeignKey("OdredisteIdLokacija");

                    b.HasOne("PutniNalogAPI.Models.Lokacije", "Polaziste")
                        .WithMany("PutniNalogPolaziste")
                        .HasForeignKey("PolazisteIdLokacija");

                    b.Navigation("Auti");

                    b.Navigation("Odrediste");

                    b.Navigation("Polaziste");
                });

            modelBuilder.Entity("PutniNalogAPI.Models.Troskovi", b =>
                {
                    b.HasOne("PutniNalogAPI.Models.PutniNalog", "PutniNalog")
                        .WithMany("Troskovis")
                        .HasForeignKey("PutniNalogIdPutniNalog");

                    b.Navigation("PutniNalog");
                });

            modelBuilder.Entity("PutniNalogAPI.Models.Auti", b =>
                {
                    b.Navigation("PutniNalogs");
                });

            modelBuilder.Entity("PutniNalogAPI.Models.Korisnici", b =>
                {
                    b.Navigation("KorisniciNalogs");
                });

            modelBuilder.Entity("PutniNalogAPI.Models.Lokacije", b =>
                {
                    b.Navigation("PutniNalogOdrediste");

                    b.Navigation("PutniNalogPolaziste");
                });

            modelBuilder.Entity("PutniNalogAPI.Models.PutniNalog", b =>
                {
                    b.Navigation("KorisniciNalogs");

                    b.Navigation("Troskovis");
                });
#pragma warning restore 612, 618
        }
    }
}
